create database passwords;
create table password ( id INT(6) AUTO_INCREMENT PRIMARY KEY, HOST VARCHAR(50) NOT NULL UNIQUE, USERNAME VARCHAR(50), EMAIL VARCHAR(50), PASSWORD VARCHAR(50), 2FA VARCHAR(50), BACKUP VARCHAR(50), OTHER VARCHAR(50) );
